run:
  timeout: 5m
  # Skip directories with multiple main functions
  skip-dirs:
    - examples
    - scripts
  # Skip building these directories
  build-tags:
    - "!examples"
    - "!scripts"

linters-settings:
  typecheck:
    # Skip type checking for example files that have multiple main functions
    skip-files:
      - "examples/.*\\.go$"
      - "scripts/.*\\.go$"

issues:
  # Exclude example files from linting
  exclude-rules:
    - path: "examples/"
      linters:
        - typecheck
    - path: "scripts/"
      linters:
        - typecheck

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - gocyclo
    - goconst
    - gocritic
    - gosec
    - revive
    - typecheck
