run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - misspell
    - typecheck
    - predeclared
  disable:
    - unused
    - gocyclo
    - goconst
    - gocritic
    - gosec
    - revive

linters-settings:
  gocyclo:
    min-complexity: 30  # Reduced from 50 to be less strict
  goconst:
    min-len: 3          # Reduced from 5 to be less strict
    min-occurrences: 3  # Reduced from 5 to be less strict
  misspell:
    locale: US
